baseURL = 'https://fabienducret.github.io'
languageCode = 'en-us'
title = 'Clean blog'
subtitle = 'subtitle'
theme = 'paper'
publishDir = 'docs'
defaultContentLanguage = 'fr'

#disqusSortname = "clean-blog-4"

[params]
  github = "fabienducret"
  monoDarkIcon = true
  name = "Bienvenue sur mon blog tech"
  bio = "Ces articles sont écrits par un passionné pour des passionnés."
  #avatar = "https://deno.land/logo.svg"